language: rust
cache: cargo
install:
  - rustup target add wasm32-unknown-unknown
script:
  - cargo web deploy --release
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: test-travis
  target-branch: gh-pages
  local-dir: target/deploy
